version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
    assignees:
      - "mfridman"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
    assignees:
      - "mfridman"
